### ISSUE TITLE
clarification on Icon

### ISSUE THREAD

**Issue by MaxChinni** [AsteroidOS/asteroid-helloworld#14]
Could you please clarify how can I include my own custom icon for the app?

Thank you.

**Comment by MaxChinni** [comment]
I tried this way and it's working, but is it a good choice?

I created a custom directory with my svg icon file:

    src/assets/swirled-shell.svg

Then I modified `src/CMakeLists.txt` adding this line

    install(FILES assets/swirled-shell.svg DESTINATION "/usr/share/icons/asteroid/")

Finally I modified `asteroid-helloworld.desktop.template` in order to use the new icon

    Icon=swirled-shell

**Comment by FlorentRevest** [comment]
Looks good to me yes :)

**Comment by MaxChinni** [comment]
Oh... ok great.
Thanks.
