### ISSUE TITLE
emulator

### ISSUE THREAD

**Issue by usagi87** [AsteroidOS/asteroid-helloworld#5]
Hey, I get the error: Failed to invoke: Booster: Loading invoked application failed: '/usr/bin/asteroid-helloworld: 
cannot open shared object file: No such file or directory' when trying to lauch the app.

**Comment by beroset** [comment]
It should be fixed now.  Can you make sure you have an updated SDK and try again?  See https://wiki.asteroidos.org/index.php/Creating_an_Asteroid_app#Configure_QtCreator_for_cross_compilation for detailed instructions for how to compile and run from the command line.

**Comment by beroset** [comment]
Recent improvements to both the code and the instructions have probably fixed this; reopen a new issue if you still have problems.
